### ISSUE TITLE
rename project

### ISSUE THREAD

**Issue by keyvanfatehi** [Strider-CD/docker-strider#5]
people are getting confused with other docker-related projects in the ecosystem. i think renaming the repo to "strider-in-docker" or something like that would help

**Comment by frank-dspeed** [comment]
docker strider is well all name images in that style close this crap issu and wait for my pull request because i plan to use strider and we use docker ill improve this img to today docker standarts including all the needed automations give me 1 or 2 days but close this

**Comment by keyvanfatehi** [comment]
Gladly!
