### ISSUE TITLE
Database password checked into repo

### ISSUE THREAD

**Issue by logankoester** [Strider-CD/docker-strider#8]
Looks like just a test environment, so feel free to close and ignore this issue if it was intentional, but just making sure you are aware there are Mongolab credentials checked in at https://github.com/Strider-CD/docker-strider/blob/master/Makefile#L1

**Comment by logankoester** [comment]
@keyvanfatehi ^

**Comment by keyvanfatehi** [comment]
Yeah no problem, thanks though

**Comment by logankoester** [comment]
Okay, carry on then :relieved:
